services:

  db:
    image: postgres:16
    container_name: car_rental_db
    restart: always

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile

    container_name: car_rental_backend
    restart: always

    command: python manage.py runserver 0.0.0.0:8000

    ports:
      - "8000:8000"

    env_file:
      - .env

    environment:
      DJANGO_SETTINGS_MODULE: config.settings

    depends_on:
      - db


volumes:
  postgres_data: